# Generated by Django 4.2.6 on 2023-10-23 10:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planetarium", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="astronomyshow",
            name="theme",
            field=models.ManyToManyField(
                related_name="shows", to="planetarium.showtheme"
            ),
        ),
    ]
