# Generated by Django 4.2.6 on 2023-10-23 10:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("planetarium", "0003_astronomyshow_theme"),
    ]

    operations = [
        migrations.RenameField(
            model_name="astronomyshow",
            old_name="theme",
            new_name="themes",
        ),
    ]
